module Configuration

	ALPHA = 5
	AFFILIATION_WEIGHT = 10
	AFFILIATION_THRESHOLD = 0.8
	EMAIL_WEIGHT = 100
	KEYWORD_WEIGHT = 4
	COAUTHOR_EQNAME_WEIGHT = 8
	COAUTHOR_MATCHINGNAME_WEIGHT = 6
	DEBUG = true
	
end
